Repository SWIFTSIM/swiftgalaxy, pull requests merged in 2025-06, with the labels that each got.

#42 Revamp of example data
  .github/workflows/lint_and_test.yml
  .gitignore
  MANIFEST.in
  README.rst
  codecov.yml
  docs/requirements.txt
  docs/source/eagle6_galaxy.png
  docs/source/getting_started/index.rst
  docs/source/halo_catalogues/index.rst
  docs/source/index.rst
  docs/source/masking/index.rst
  docs/source/modules/swiftgalaxy.demo_data.rst
  docs/source/modules/swiftgalaxy.rst
  docs/source/visualisation/index.rst
  eagle6_galaxy.png
  mypy.ini
  optional_requirements.txt
  pyproject.toml
  requirements.txt
  swiftgalaxy/demo_data.py
  swiftgalaxy/json/caesar_unit_registry.json
  tests/conftest.py
  tests/test_coordinate_transformations.py
  tests/test_creation.py
  tests/test_derived_coordinates.py
  tests/test_examples.py
  tests/test_halo_catalogues.py
  tests/test_iterator.py
  tests/test_masking.py
  tests/toysnap.py
Labels: documentation, enhancement

#43 Add missing narrative doc file
  docs/source/demonstration_data/index.rst
  docs/source/index.rst
Labels: bug

#18 Add CoLab example
  docs/source/index.rst
  examples/README.rst
  examples/SWIFTGalaxy_demo.ipynb
  optional_requirements.txt
  swiftgalaxy/demo_data.py
  tests/conftest.py
  tests/test_examples.py
  tests/test_halo_catalogues.py
Labels: documentation

#44 Update docs homepage
  README.rst
  docs/requirements.txt
  docs/source/citing/index.rst
  docs/source/community/index.rst
  docs/source/conf.py
  docs/source/getting_started/eagle6_galaxy.png
  docs/source/getting_started/index.rst
  docs/source/index.rst
  pyproject.toml
Labels: documentation

#48 Add missing items in catalogue tab completion, and test
  codemeta.json
  pyproject.toml
  swiftgalaxy/halo_catalogues.py
  tests/test_halo_catalogues.py
  tests/test_version.py
Labels: bug
